### ISSUE TITLE
404 error even when file is there

### ISSUE THREAD

**Issue by bsobhani** [tiagocoutinho/eiger-simulator#1]
eiger-simulator --dataset=test.h5

results in:

"INFO:     127.0.0.1:37176 - "GET / HTTP/1.1" 404 Not Found"

when I go to 127.0.0.1:8000

I also tried:

eiger-simulator --dataset=./test.h5

And I also tried writing out the whole path too (/home/.../test.h5). None of these work. test.h5 exists.

**Comment by tiagocoutinho** [comment]
Thanks for reporting @bsobhani!

Was test.h5 generated from a real eiger acquisition?
So far we are only supporting datasets that have frames compatible with eiger detector but we can improve that.

Would it possible to put test.h5 somewhere where I could download it? 

Thanks in advance

**Comment by tiagocoutinho** [comment]
Hi again @bsobhani,

I haven't noticed you tried 127.0.0.1:8000 directly.

As we don't have an eiger detector installed were I work yet, I don't know what exactly is the main eiger detector page showing (if any at all).
I will write a main page so people won't get lost when they first try this.

So far we are just simulating the REST API.
We do export automatic interactive API documentation (courtesy of [fastapi](https://fastapi.tiangolo.com/), [swagger](https://github.com/swagger-api/swagger-ui) and [redoc](https://github.com/Rebilly/ReDoc) libraries).
They are available at:
* [swagger at http://127.0.0.1:8000/docs](http://127.0.0.1:8000/docs)
* [redoc at http://127.0.0.1:8000/redoc](http://127.0.0.1:8000/redoc)

Let me know if this works.

FYI: loading the H5 file you pass in the command line is triggered by the initialize command (ie an HTTP PUT on http://127.0.0.1:8000/detector/api/1.6.0/command/initialize)

**Comment by tiagocoutinho** [comment]
Added a main page afd104b. Produced a new version 0.4.0 with this change

**Comment by tiagocoutinho** [comment]
Should be fixed
